# Generated by Django 3.2.18 on 2023-04-19 08:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurposeBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=150, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Назначение здания',
                'verbose_name_plural': 'Назначения зданий',
            },
        ),
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип работы')),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работ',
            },
        ),
        migrations.CreateModel(
            name='WorkObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=150, verbose_name='Цель работы')),
            ],
            options={
                'verbose_name': 'Цель работы',
                'verbose_name_plural': 'Цели работ',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование объекта')),
                ('address', models.CharField(max_length=500, verbose_name='Местоположение объекта')),
                ('cadastral_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Кадастровый номер'), blank=True, null=True, size=None, verbose_name='Кадастровые номера')),
                ('coords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, verbose_name='Координаты'), size=None, verbose_name='Координаты')),
                ('square', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Площадь участка')),
                ('project_organisation', models.CharField(max_length=200, verbose_name='Проектная организация')),
                ('general_contractor', models.CharField(max_length=200, verbose_name='Генподрядчик')),
                ('customer', models.CharField(max_length=200, verbose_name='Заказчик')),
                ('year', models.IntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023, verbose_name='Год изысканий')),
                ('status', models.CharField(choices=[('completed', 'Выполнен'), ('not completed', 'Не выполнен')], default='completed', max_length=20, verbose_name='Статус заказа')),
                ('purpose_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.purposebuilding', verbose_name='Назначение здания')),
                ('type_work', models.ManyToManyField(related_name='orders', to='expert.TypeWork', verbose_name='Виды работ')),
                ('work_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.workobjective', verbose_name='Цель работы')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]