# Generated by Django 3.2.18 on 2023-04-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_auto_20230419_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purposebuilding',
            options={'verbose_name': 'Назначение объекта', 'verbose_name_plural': 'Назначения объектов'},
        ),
        migrations.AlterField(
            model_name='order',
            name='general_contractor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Генподрядчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purpose_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expert.purposebuilding', verbose_name='Назначение объекта'),
        ),
    ]
