# Generated by Django 3.2.18 on 2023-04-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_auto_20230419_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='purpose_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='expert.purposebuilding', verbose_name='Назначение объекта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='research_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='expert.researchpurpose', verbose_name='Цель изысканий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='expert.workobjective', verbose_name='Градостроительная деятельность'),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='expert.location', verbose_name='Локация'),
        ),
    ]
