# Generated by Django 3.2.18 on 2023-04-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_auto_20230419_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='project_organisation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Проектная организация'),
        ),
        migrations.AlterField(
            model_name='order',
            name='square',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Площадь участка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.IntegerField(blank=True, choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], null=True, verbose_name='Год изысканий'),
        ),
    ]
