# Generated by Django 3.2.18 on 2023-04-20 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0006_auto_20230419_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='order_images')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='expert.order', verbose_name='Заказ')),
            ],
        ),
    ]
