# Generated by Django 3.2.18 on 2023-04-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0010_auto_20230426_0831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderFile',
            new_name='CurrentOrderFile',
        ),
    ]
