# Generated by Django 3.2.18 on 2023-05-03 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0012_auto_20230503_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurposeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название группы')),
            ],
        ),
        migrations.AddField(
            model_name='purposebuilding',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purpose_group', to='expert.purposegroup', verbose_name='Группа назначений'),
        ),
    ]
